version: 2

jobs:
  clang-format:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install container dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y clang-format
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Check clang-format
          command: yarn clang-format:check


workflows:
  version: 2
  build-test-lint:
    jobs:
      - clang-format
